site_name: eXercise OPEN CALL PROJECT

nav:
  - Introduction: index.md
  - Hugging Face: huggingface.md
  - Unity DLL: unity.md

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.instant
    - header.autohide
    - toc.follow
  logo: assets/images/logo.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-repo
